AWSTemplateFormatVersion: 2010-09-09
Parameters:
  GitRepoName:
    Type: String
    Description: "Addon name, please use no space word"
    MaxLength: '255'
    MinLength: '2'
    AllowedPattern: "^[a-zA-Z0-9-_]*$"
    Default: VeeamS3
  AppName:
    Description:  (Required) Enter Application Name.
    Type: String
    AllowedPattern: "[^\\s]+"
    ConstraintDescription: "application name tag min 3 and max 50 characters"
    MinLength: 3
    MaxLength: 50
    Default: HQ_Veeam_BackupAndReplication
  UAI:
    Description:  (Required) Enter ServiceNow ID.
    Type: String
    AllowedPattern: "[^\\s]+"
    ConstraintDescription: " uai tag min 3 and max 50 characters"
    MinLength: 3
    MaxLength: 50
  DevelopmentAccount:
    Description: Development Account Number
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cicd/xxx/Development/accountnumber
  QAAccount:
    Description: Enter Account Number of QA Environment
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cicd/xxx/QA/accountnumber
  SandboxAccount:
     Description: Enter Account Number of Sandbox Environment
     Type: AWS::SSM::Parameter::Value<String>
     Default: /cicd/xxx/Sandbox/accountnumber
  NonProdAccount:
     Type: AWS::SSM::Parameter::Value<String>
     Default: /cicd/xxx/Non-Production/accountnumber
  ProductionAccount:
     Description: Enter Account Number of Production Environment
     Type: AWS::SSM::Parameter::Value<String>
     Default: /cicd/xxx/Production/accountnumber
  AppROLE:
    Type: String
    Default: "app"
  StackName:
    Description: Name of the Stack in each AccountId
    Type: String
    Default: 'Veeam'

Resources:
  ResolveCICDKMSUS:
    Type: Custom::get-kms-arn
    Properties:
      ServiceToken: !Join
        - ':'
        - - 'arn:aws:lambda'
          - !Ref AWS::Region
          - !Ref AWS::AccountId
          - 'get-kms-arn'
      KeyAlias: 'alias/cicd-kmskey'
      Region: "us-east-1"
  ResolveCICDKMSEU:
    Type: Custom::get-kms-arn
    Properties:
      ServiceToken: !Join
        - ':'
        - - 'arn:aws:lambda'
          - !Ref AWS::Region
          - !Ref AWS::AccountId
          - 'get-kms-arn'
      KeyAlias: 'alias/cicd-kmskey'
      Region: "eu-west-1"
  CodeBuildCfnNag:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      Name: !Sub CodeBuildCfnNag-${AppName}
      Description: Download scripts and Run CFN_NAG on templates
      ServiceRole: !Sub arn:aws:iam::${AWS::AccountId}:role/CICD-CodeBuildService-Role
      EncryptionKey: !Sub arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/${ResolveCICDKMSUS.key_id}
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: 'aws/codebuild/ruby:2.5.3'
        EnvironmentVariables:
          -
            Name: REGION_NAME
            Value: !Ref 'AWS::Region'
          -
            Name: ACCOUNT_ID
            Value: !Ref 'AWS::AccountId'
      Source:
        Type: CODEPIPELINE
        BuildSpec: |
          version: 0.2
          phases:
            install:
              commands:
                - export current=`pwd`
                - apt-get -y update
                - gem install cfn-nag
                - apt-get install -y dos2unix
            build:
              commands:
                - |
                  #!/bin/bash
                  for f in templates/*.yaml
                  do
                      if cfn_nag_scan --input-path "$f"; then
                          echo "$f PASSED"
                      else
                          echo "$f FAILED"
                          touch FAILED
                      fi
                  done
                  if [ -e FAILED ]; then
                    echo cfn-nag FAILED at least once!
                    exit 1
                  else
                    echo cfn-nag PASSED on all files!
                    exit 0
                  fi
      TimeoutInMinutes: 10
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub ${GitRepoName}-Pipeline
      RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/CICD-PipelineService-Role
      ArtifactStores:
        - Region: us-east-1
          ArtifactStore:
            Type: S3
            Location: !Sub cicd-pipeline-artifacts-${AWS::AccountId}-us-east-1
            EncryptionKey:
              Id: !GetAtt ResolveCICDKMSUS.key_id
              Type: KMS
        - Region: eu-west-1
          ArtifactStore:
            Type: S3
            Location: !Sub cicd-pipeline-artifacts-${AWS::AccountId}-eu-west-1
            EncryptionKey:
              Id: !GetAtt ResolveCICDKMSEU.key_id
              Type: KMS
      Stages:
        - Name: SourceStageCodeCommit
          Actions:
            - Name: TemplateSource
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: S3
                Version: '1'
              Configuration:
                S3Bucket: !Sub ${AWS::AccountId}-${AWS::Region}-cicd-src
                PollForSourceChanges: True
                S3ObjectKey: !Sub ${GitRepoName}.zip
              OutputArtifacts:
                - Name: SourceArtifacts
              RunOrder: 1
        - Name: PreDeployTests
          Actions:
            - InputArtifacts:
                - Name: SourceArtifacts
              Name: DownloadScriptsAndRuncfnNag
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: '1'
                Provider: CodeBuild
              OutputArtifacts:
                - Name: DownloadScripts
              Configuration:
                ProjectName: !Ref CodeBuildCfnNag
              RunOrder: 1
        - Name: DeploytoDev
          Actions:
            - Name: VeeamVPCEndPointEU
              RunOrder: 1
              InputArtifacts:
                - Name: SourceArtifacts
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: '1'
                Provider: CloudFormation
              Region: eu-west-1
              RoleArn: !Sub 'arn:aws:iam::${DevelopmentAccount}:role/CICD-Deployment-Role'
              Configuration:
                ActionMode: REPLACE_ON_FAILURE
                RoleArn: !Sub "arn:aws:iam::${DevelopmentAccount}:role/CICD-Cloudformation-Role"
                Capabilities: CAPABILITY_NAMED_IAM
                StackName: !Sub ${StackName}-Endpoints
                TemplatePath: SourceArtifacts::teamplates/Veeam-endpoints.yaml
                TemplateConfiguration: SourceArtifacts::parameters/Veeam-endpoints-dev-eu-west-1.json
                ParameterOverrides: !Sub |
                  {
                    "UAI": "${UAI}",
                    "ENV": "dev"
                  }
            - Name: VeeamVPCEndPointUS
              RunOrder: 1
              InputArtifacts:
                - Name: SourceArtifacts
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: '1'
                Provider: CloudFormation
              Region: us-east-1
              RoleArn: !Sub 'arn:aws:iam::${DevelopmentAccount}:role/CICD-Deployment-Role'
              Configuration:
                ActionMode: REPLACE_ON_FAILURE
                RoleArn: !Sub "arn:aws:iam::${DevelopmentAccount}:role/CICD-Cloudformation-Role"
                Capabilities: CAPABILITY_NAMED_IAM
                StackName: !Sub ${StackName}-Endpoints
                TemplatePath: SourceArtifacts::teamplates/Veeam-endpoints.yaml
                TemplateConfiguration: SourceArtifacts::parameters/Veeam-endpoints-dev-us-east-1.json
                ParameterOverrides: !Sub |
                  {
                    "UAI": "${UAI}",
                    "ENV": "dev"
                  }
        - Name: Approval-QA
          Actions:
          - InputArtifacts: []
            Name: Approval
            ActionTypeId:
              Category: Approval
              Owner: AWS
              Version: '1'
              Provider: Manual
            OutputArtifacts: []
            Configuration: {}
            RunOrder: 1
