# Requirements on the target accounts:
# - VPC: number of security groups per network interface > 6 (suggested: 10)
# - VPC: number of routes per route table  > 50 (suggested: 125)

AWSTemplateFormatVersion: 2010-09-09
Description: DEV account 733344274048 Veeam infrastructure CICD Pipeline
Parameters:
  GitRepoName:
    Description: (Required) Name of the GitHub repository name and zip archive in CICD S3 bucket
    Type: String
    Default: "VeeamS3"
  app:
    Description: (Required) Enter Application Name
    Type: String
    AllowedPattern: "[^\\s]+"
    ConstraintDescription: "application name tag min 3 and max 50 characters"
    MinLength: 3
    MaxLength: 50
    Default: "HQ_Veeam_BackupAndReplication"
  uai:
    Description: (Required) Enter ServiceNow ID
    Type: String
    AllowedPattern: "[^\\s]+"
    ConstraintDescription: " uai tag min 3 and max 50 characters"
    MinLength: 3
    MaxLength: 50
    Default: "uai1100712327"
  role:
   Description: (Required) Enter the role of the component. i.e 'admin-resource'
   Type: String
   AllowedValues:
     - web
     - app
     - database
     - auth
     - emr
     - other
   Default: other
  env:
    Description: (Required) Select the enviroment of the resource
    Type: String
    AllowedValues:
      - prod
      - stg
      - qa
      - dev
    Default: dev
  Owner:
    Type: String
    AllowedPattern: ^.+$
    Description: "(Required) Veeam Owner / provider (email)"
  TargetAccount:
    Description: (Required) Enter Account Number of the Desired Application Environment
    Type: String
    Default: "733344274048"
  TargetVPC:
    Type: String
    AllowedPattern: ^.+$
    Description: "(Required) Target Veeam vpc"
    Default: "vpc-009e5a5dab69ff15b"
  TargetMyVeeamS3BucketBHUKCTO1:
    Type: String
    AllowedPattern: ^.+$
    Description: "(Required) Baker Hughes, United Kingdom(Not EU), CTO product line, 001=First bucket in UK"
    Default: "bh-uk-cto001"
  TargetMyVeeamS3BucketBHUKPPS1:
    Type: String
    AllowedPattern: ^.+$
    Description: "(Required) Baker Hughes, UK, Pipeline Services"
    Default: "bh-uk-pps001"
  TargetMyVeeamS3BucketBHNACTO1:
    Type: String
    AllowedPattern: ^.+$
    Description: "(Required) Baker Hughes, North America, CTO product line, 001=First bucket in NA"
    Default: "bh-na-cto001"    
  MyVeeamVersion:
    Type: String
    AllowedPattern: ^.+$
    Description: "(Required) MyVeeam version and S3 repository key"
    Default: "2112121"
  UpdateParameter:
    Description: (Optional) Update parameter for service catalog products
    Type: String
  MyVeeamProductVersion:
    Description: (Optional) MyVeeam Product version. Specify to create a new version
    Type: String
    Default: 1

Resources:
  ResolveCICDKMS:
    Type: Custom::get-kms-arn
    Properties:
      ServiceToken: !Join
        - ':'
        - - 'arn:aws:lambda'
          - !Ref AWS::Region
          - !Ref AWS::AccountId
          - 'get-kms-arn'
      KeyAlias: 'alias/cicd-kmskey'

  CodeBuildCfnNag:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      Name: !Sub "CodeBuildCfnNag-MyVeeam-${MyVeeamVersion}-${TargetAccount}"
      Description: Download scripts and Run CFN_NAG on templates
      ServiceRole: !Sub 'arn:aws:iam::${AWS::AccountId}:role/CICD-CodeBuildService-Role'
      EncryptionKey: !Sub arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/${ResolveCICDKMS.key_id}
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: 'aws/codebuild/ruby:2.5.3'
        EnvironmentVariables:
          - Name: REGION_NAME
            Value: !Ref 'AWS::Region'
          - Name: ACCOUNT_ID
            Value: !Ref 'AWS::AccountId'
      Source:
        Type: CODEPIPELINE
        BuildSpec: |
          version: 0.2
          phases:
            install:
              commands:
                - export current=`pwd`
                - apt-get -y update
                - gem install cfn-nag
                - apt-get install -y dos2unix
            pre_build:
              commands:
                - export LC_ALL="en_US.UTF-8"
                - locale-gen en_US en_US.UTF-8
                - dpkg-reconfigure locales
            build:
              commands:
                - |
                  #!/bin/bash
                  find . -ls
                  for f in ./*.yaml
                  do
                      if cfn_nag_scan --input-path "$f"; then
                          echo "$f PASSED"
                      else
                          echo "$f FAILED"
                          touch FAILED
                      fi
                  done

                  if [ -e FAILED ]; then
                    echo cfn-nag FAILED at least once!
                    exit 1
                  else
                    echo cfn-nag PASSED on all files!
                    exit 0
                  fi
      TimeoutInMinutes: 10
  MyVeeamInfraPipeline:
    Type: 'AWS::CodePipeline::Pipeline'
    Properties:
      Name: !Sub 'MyVeeam-${MyVeeamVersion}-${TargetAccount}-Infra-Pipeline'
      RoleArn: !Sub 'arn:aws:iam::${AWS::AccountId}:role/CICD-PipelineService-Role'
      ArtifactStore:
        Type: S3
        Location: !Sub 'cicd-pipeline-artifacts-${AWS::AccountId}-${AWS::Region}'
        EncryptionKey:
          Id: !GetAtt ResolveCICDKMS.key_id
          Type: KMS
      Stages:
        - Name: Source
          Actions:
            - Name: MyVeeam-Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: S3
                Version: '1'
              Configuration:
                S3Bucket: !Sub '${AWS::AccountId}-${AWS::Region}-cicd-src'
                PollForSourceChanges: true
                S3ObjectKey: !Sub '${GitRepoName}.zip'
              OutputArtifacts:
                - Name: SourceArtifacts
              RunOrder: 1

        - Name: MyVeeam-StartApprovalStage
          Actions:
          - Name: MyVeeam-StartApprovalStage
            ActionTypeId:
              Category: Approval
              Owner: AWS
              Version: '1'
              Provider: Manual
            InputArtifacts: []
            OutputArtifacts: []
            Configuration:
              CustomData: !Sub "Please approve before starting MyVeeam ${MyVeeamVersion} infrastructure pipeline"
            RunOrder: 2

#        - Name: CFTTemplateScan
#          Actions:
#            - InputArtifacts:
#                - Name: SourceArtifacts
#              Name: DownloadScriptsAndRuncfnNag
#              ActionTypeId:
#                Category: Build
#                Owner: AWS
#                Version: '1'
#                Provider: CodeBuild
#              OutputArtifacts:
#                - Name: DownloadScripts
#              Configuration:
#                ProjectName: !Ref CodeBuildCfnNag
#              RunOrder: 2

        - Name: MyVeeam-VPC
          Actions:
            - Name: MyVeeam-Endpoints
              RunOrder: 3
              InputArtifacts:
                - Name: SourceArtifacts
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: '1'
                Provider: CloudFormation
              RoleArn: !Sub 'arn:aws:iam::${TargetAccount}:role/CICD-Deployment-Role'
              Configuration:
                ActionMode: CREATE_UPDATE
                RoleArn: !Sub >-
                  arn:aws:iam::${TargetAccount}:role/CICD-Cloudformation-Role
                Capabilities: CAPABILITY_NAMED_IAM
                StackName: !Sub MyVeeam-Endpoints-${MyVeeamVersion}
                TemplatePath: SourceArtifacts::MyVeeam-endpoints.yaml
                ParameterOverrides: !Sub |
                  {
                    "TargetVPC": "${TargetVPC}",
                    "UpdateParameter": "${UpdateParameter}",
                    "app": "${app}",
                    "uai": "${uai}",
                    "role": "${role}",
                    "env": "${env}"
                  }
        - Name: MyVeeam-S3Bucket
          Actions:
            - Name: MyVeeam-S3CreateBucket
              RunOrder: 3
              InputArtifacts:
                - Name: SourceArtifacts
              Namespace: MyVeeamBucket
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: '1'
                Provider: CloudFormation
              RoleArn: !Sub 'arn:aws:iam::${TargetAccount}:role/CICD-Deployment-Role'
              Configuration:
                ActionMode: CREATE_UPDATE
                RoleArn: !Sub >-
                  arn:aws:iam::${TargetAccount}:role/CICD-Cloudformation-Role
                Capabilities: CAPABILITY_NAMED_IAM
                StackName: !Sub MyVeeam-S3CreateBucket-${MyVeeamVersion}
                TemplatePath: SourceArtifacts::MyVeeam-create-S3-bucket.yaml
                ParameterOverrides: !Sub |
                  {
                    "BucketName1": "${TargetMyVeeamS3BucketBHUKCTO1}-${MyVeeamVersion}",
                    "BucketName2": "${TargetMyVeeamS3BucketBHUKPPS1}-${MyVeeamVersion}",
                    "BucketName3": "${TargetMyVeeamS3BucketBHNACTO1}-${MyVeeamVersion}",
                    "DataClassification": "confidential/highly-confidential",
                    "UpdateParameter": "${UpdateParameter}",
                    "app": "${app}",
                    "uai": "${uai}",
                    "role": "${role}",
                    "env": "${env}"
                  }

#                    "IamRoleName": "#{MyHPCNFS.NFSRoleName}",
Outputs:
  PipelineUrl:
    Value: !Sub >-
      https://console.aws.amazon.com/codepipeline/home?region=${AWS::Region}#/view/${MyVeeamInfraPipeline}