AWSTemplateFormatVersion: '2010-09-09'
Description: This template creates an S3 bucket on the application account.
Parameters:
  UpdateParameter:
    Description: (optional) This parameter is a fake param please use/change it just if you want to force the update to the new SC version
    Type: String
    Default: ""
  BucketName1:
    Type: String
    Default: ""
  BucketName2:
    Type: String
    Default: ""
  BucketName3:
    Type: String
    Default: ""
  DataClassification:
    Type: String
    Default: ""
  FirstTransitionStorageClass:
    Description: Select storage class to which you want the object to transition. It's recommended to transition objects to STANDARD_IA storage class after 30 days.
    Type: String
    AllowedValues: [ DEEP_ARCHIVE , GLACIER , INTELLIGENT_TIERING , ONEZONE_IA , STANDARD_IA ]
    Default: STANDARD_IA
  FirstTransitionInDays:
    Description: Indicates the number of days after creation when objects are transitioned to the specified storage class. The value must be a positive integer. It's recommended to keep it 30 days.
    Type: Number
#    Default: 30
    Default: 10950
  SecondTransitionStorageClass:
    Description: Select storage class to which you want the object to transition. It's recommended to transition objects to GLACIER storage class after 90 days as a second transition.
    Type: String
    AllowedValues: [ DEEP_ARCHIVE , GLACIER , INTELLIGENT_TIERING , ONEZONE_IA , STANDARD_IA ]
    Default: GLACIER
  SecondTransitionInDays:
    Description: Indicates the number of days after creation when objects are transitioned to the specified storage class. The value must be a positive integer. It's recommended to keep it 90 days as a second transition.
    Type: Number
#    Default: 365
    Default: 20950
  ThirdTransitionInDays:
    Description: Indicates the number of days after creation when objects are transitioned to the specified storage class. The value must be a positive integer. It's recommended to keep it 365 days as a third transition.
    Type: Number
#    Default: 1825
    Default: 30950
  ThirdTransitionStorageClass:
    Description: Select storage class to which you want the object to transition. It's recommaneded to transtion objects to GLACIER Deep Achieve storage class after 365 days as a third transtion.
    Type: String
    AllowedValues: [ DEEP_ARCHIVE , GLACIER , INTELLIGENT_TIERING , ONEZONE_IA , STANDARD_IA ]
    Default: DEEP_ARCHIVE
  ExpirationInDays:
    Description: Specify the lifecycle of the objects in an Amazon S3 bucket in days, after the expiration period the objects will be deleted from the bucket. It's recommended to keep it 365*30 days.
    Type: Number
#    Default: 10950
    Default: 40950
  LifeCycleId:
    Description: Specify a unique identifier for the s3 objects life cycle rules. The value can't be longer than 255 characters. (Mandatory)
    Type: String
    Default: ObjectsLifeCycle
  IamRoleName:
    Type: 'String'
    Description: 'Enter the IAM Role Names - separated by a comma - that will have access to this bucket also through API. (Optional)'
    Default: ""
  uai:
    Type: String
  app:
    Type: String
  role:
    Type: String
    Default: "app"
  env:
    Type: String
    Default: "dev"
Resources:
  CreateBucketForApplication1:
    Type: "AWS::ServiceCatalog::CloudFormationProvisionedProduct"
    Properties:
      ProductName: "S3Bucket"
      ProvisioningArtifactName: "{{resolve:ssm:/ServiceCatalog/S3Bucket/LatestVersion:1}}"
      ProvisioningParameters:
        - Key: "app"
          Value: !Ref app
        - Key: "uai"
          Value: !Ref uai
        - Key: "role"
          Value: !Ref role
        - Key: "env"
          Value: !Ref env
        - Key: "DataClassification"
          Value: !Ref DataClassification
        - Key: "IamRoleName"
          Value: !Ref IamRoleName
        - Key: "S3BucketName"
          Value: !Join ["",[!Ref "BucketName1","-",!Ref "env","-","src"]]
        - Key: "UpdateParameter"
          Value: "Yes"
#        - Key: "UpdateParameter"
#          Value: !Ref UpdateParameter
        - Key: FirstTransitionStorageClass
          Value: !Ref FirstTransitionStorageClass
        - Key: FirstTransitionInDays
          Value: !Ref FirstTransitionInDays
        - Key: SecondTransitionStorageClass
          Value: !Ref SecondTransitionStorageClass
        - Key: SecondTransitionInDays
          Value: !Ref SecondTransitionInDays
        - Key: ThirdTransitionStorageClass
          Value: !Ref ThirdTransitionStorageClass
        - Key: ThirdTransitionInDays
          Value: !Ref ThirdTransitionInDays
        - Key: ExpirationInDays
          Value: !Ref ExpirationInDays
        - Key: LifeCycleId
          Value: !Ref LifeCycleId
  CreateBucketForApplication2:
    Type: "AWS::ServiceCatalog::CloudFormationProvisionedProduct"
    Properties:
      ProductName: "S3Bucket"
      ProvisioningArtifactName: "{{resolve:ssm:/ServiceCatalog/S3Bucket/LatestVersion:1}}"
      ProvisioningParameters:
        - Key: "app"
          Value: !Ref app
        - Key: "uai"
          Value: !Ref uai
        - Key: "role"
          Value: !Ref role
        - Key: "env"
          Value: !Ref env
        - Key: "DataClassification"
          Value: !Ref DataClassification
        - Key: "IamRoleName"
          Value: !Ref IamRoleName
        - Key: "S3BucketName"
          Value: !Join ["",[!Ref "BucketName2","-",!Ref "env","-","src"]]
        - Key: "UpdateParameter"
          Value: "Yes"
#        - Key: "UpdateParameter"
#          Value: !Ref UpdateParameter
        - Key: FirstTransitionStorageClass
          Value: !Ref FirstTransitionStorageClass
        - Key: FirstTransitionInDays
          Value: !Ref FirstTransitionInDays
        - Key: SecondTransitionStorageClass
          Value: !Ref SecondTransitionStorageClass
        - Key: SecondTransitionInDays
          Value: !Ref SecondTransitionInDays
        - Key: ThirdTransitionStorageClass
          Value: !Ref ThirdTransitionStorageClass
        - Key: ThirdTransitionInDays
          Value: !Ref ThirdTransitionInDays
        - Key: ExpirationInDays
          Value: !Ref ExpirationInDays
        - Key: LifeCycleId
          Value: !Ref LifeCycleId
  CreateBucketForApplication3:
    Type: "AWS::ServiceCatalog::CloudFormationProvisionedProduct"
    Properties:
      ProductName: "S3Bucket"
      ProvisioningArtifactName: "{{resolve:ssm:/ServiceCatalog/S3Bucket/LatestVersion:1}}"
      ProvisioningParameters:
        - Key: "app"
          Value: !Ref app
        - Key: "uai"
          Value: !Ref uai
        - Key: "role"
          Value: !Ref role
        - Key: "env"
          Value: !Ref env
        - Key: "DataClassification"
          Value: !Ref DataClassification
        - Key: "IamRoleName"
          Value: !Ref IamRoleName
        - Key: "S3BucketName"
          Value: !Join ["",[!Ref "BucketName3","-",!Ref "env","-","src"]]
        - Key: "UpdateParameter"
          Value: "Yes"
#        - Key: "UpdateParameter"
#          Value: !Ref UpdateParameter
        - Key: FirstTransitionStorageClass
          Value: !Ref FirstTransitionStorageClass
        - Key: FirstTransitionInDays
          Value: !Ref FirstTransitionInDays
        - Key: SecondTransitionStorageClass
          Value: !Ref SecondTransitionStorageClass
        - Key: SecondTransitionInDays
          Value: !Ref SecondTransitionInDays
        - Key: ThirdTransitionStorageClass
          Value: !Ref ThirdTransitionStorageClass
        - Key: ThirdTransitionInDays
          Value: !Ref ThirdTransitionInDays
        - Key: ExpirationInDays
          Value: !Ref ExpirationInDays
        - Key: LifeCycleId
          Value: !Ref LifeCycleId
Outputs:
  S3BucketName1:
    Description: S3 Bucket Name BH-UK-CTO001 
    Value: !GetAtt 'CreateBucketForApplication1.Outputs.S3BucketName'
  S3BucketName2:
    Description: S3 Bucket Name BH-UK-PPS001
    Value: !GetAtt 'CreateBucketForApplication2.Outputs.S3BucketName'
  S3BucketName3:
    Description: S3 Bucket Name BH-NA-CTO001 
    Value: !GetAtt 'CreateBucketForApplication3.Outputs.S3BucketName'
